# Generated by Django 4.1.7 on 2023-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('release_date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=3, max_digits=3)),
                ('plot', models.CharField(max_length=512)),
            ],
        ),
    ]
